#!/bin/bash

echo "=== Download Queue Management Testing - Logcat Commands ==="
echo ""
echo "1. Monitor Queue Manager Worker:"
echo "adb logcat -s DownloadQueueManagerWorker"
echo ""
echo "2. Monitor Download Queue Manager:"
echo "adb logcat -s DownloadQueueManager"
echo ""
echo "3. Monitor All Download Activity:"
echo "adb logcat | grep -E '(DownloadQueue|AudioDownload|WorkManager)'"
echo ""
echo "4. Monitor WorkManager Activity:"
echo "adb logcat -s WM-WorkerWrapper"
echo ""
echo "5. Combined Download Monitoring:"
echo "adb logcat -s DownloadQueueManagerWorker,DownloadQueueManager,AudioDownloadWorker,WorkManagerTestViewModel"
echo ""
echo "=== Expected Log Patterns ==="
echo "✅ Queue processing started:"
echo "D/DownloadQueueManager: Starting periodic download queue processing"
echo ""
echo "✅ Worker execution:"
echo "D/DownloadQueueManagerWorker: Starting download queue processing"
echo "D/DownloadQueueManagerWorker: Currently running downloads: X/3"
echo ""
echo "✅ Queue processing:"
echo "D/DownloadQueueManagerWorker: Available download slots: X"
echo "D/DownloadQueueManagerWorker: Enqueued download worker for: [recording]/[track]"
echo ""
echo "✅ Worker cleanup:"
echo "D/DownloadQueueManagerWorker: Cancelling orphaned worker for download: [id]"