name: Build Dead Archive APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3.2.2
      
    - name: Cache Gradle packages
      uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Gradle
      uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0
      with:
        gradle-version: 8.14.2
        
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Build debug APK
      run: gradle assembleDebug --stacktrace
      
    - name: Build release APK
      run: gradle assembleRelease --stacktrace
      
    - name: Run tests
      run: gradle test --stacktrace
      
    - name: Run lint checks
      run: gradle lint --stacktrace
      
    - name: Generate build info
      run: |
        echo "BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
        echo "COMMIT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
        echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        
    - name: Upload debug APK artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dead-archive-debug-${{ env.COMMIT_SHA }}
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload release APK artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dead-archive-release-${{ env.COMMIT_SHA }}
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 90
        
    - name: Upload lint reports
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: lint-reports-${{ env.COMMIT_SHA }}
        path: |
          app/build/reports/lint-results*.html
          app/build/reports/lint-results*.xml
        retention-days: 14
        
    - name: Upload test reports
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: test-reports-${{ env.COMMIT_SHA }}
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 14