name: Build Dead Archive APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Run tests
      run: ./gradlew test --stacktrace
      
    - name: Run lint checks
      run: ./gradlew lint --stacktrace
      
    - name: Generate build info
      run: |
        echo "BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
        echo "COMMIT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
        echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        
    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: dead-archive-debug-${{ env.COMMIT_SHA }}
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: dead-archive-release-${{ env.COMMIT_SHA }}
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 90
        
    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports-${{ env.COMMIT_SHA }}
        path: |
          app/build/reports/lint-results*.html
          app/build/reports/lint-results*.xml
        retention-days: 14
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ env.COMMIT_SHA }}
        path: |
          app/build/reports/tests/
          app/build/test-results/
        retention-days: 14